// <auto-generated />
using System;
using HondaSensorChecker.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HondaSensorChecker.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260131233207_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("HondaSensorChecker.Models.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LogId");

                    b.HasIndex("OperatorId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("HondaSensorChecker.Models.Operator", b =>
                {
                    b.Property<int>("OperatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Admin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Re")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZfId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OperatorId");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("HondaSensorChecker.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndPartNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartPartNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("HondaSensorChecker.Models.SapWorkOrder", b =>
                {
                    b.Property<int>("SapWorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SapWorkOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("SapWorkOrders");
                });

            modelBuilder.Entity("HondaSensorChecker.Models.Sensor", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SapWorkOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScannedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierBoxId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZfBoxId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SensorId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SapWorkOrderId");

                    b.HasIndex("SupplierBoxId");

                    b.HasIndex("ZfBoxId");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("HondaSensorChecker.Models.SupplierBox", b =>
                {
                    b.Property<int>("SupplierBoxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QtyRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QtySupplied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniqueNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SupplierBoxId");

                    b.HasIndex("ProductId");

                    b.ToTable("SupplierBoxes");
                });

            modelBuilder.Entity("HondaSensorChecker.Models.ZfBox", b =>
                {
                    b.Property<int>("ZfBoxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QtyToSend")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SapWorkOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniqueNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("ZfBoxId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SapWorkOrderId");

                    b.ToTable("ZfBoxes");
                });

            modelBuilder.Entity("HondaSensorChecker.Models.Log", b =>
                {
                    b.HasOne("HondaSensorChecker.Models.Operator", "Operator")
                        .WithMany("Logs")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("HondaSensorChecker.Models.SapWorkOrder", b =>
                {
                    b.HasOne("HondaSensorChecker.Models.Product", "Product")
                        .WithMany("SapWorkOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HondaSensorChecker.Models.Sensor", b =>
                {
                    b.HasOne("HondaSensorChecker.Models.Operator", "Operator")
                        .WithMany("Sensors")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HondaSensorChecker.Models.Product", "Product")
                        .WithMany("Sensors")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HondaSensorChecker.Models.SapWorkOrder", "SapWorkOrder")
                        .WithMany("Sensors")
                        .HasForeignKey("SapWorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HondaSensorChecker.Models.SupplierBox", "SupplierBox")
                        .WithMany("Sensors")
                        .HasForeignKey("SupplierBoxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HondaSensorChecker.Models.ZfBox", "ZfBox")
                        .WithMany("Sensors")
                        .HasForeignKey("ZfBoxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operator");

                    b.Navigation("Product");

                    b.Navigation("SapWorkOrder");

                    b.Navigation("SupplierBox");

                    b.Navigation("ZfBox");
                });

            modelBuilder.Entity("HondaSensorChecker.Models.SupplierBox", b =>
                {
                    b.HasOne("HondaSensorChecker.Models.Product", "Product")
                        .WithMany("SupplierBoxes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HondaSensorChecker.Models.ZfBox", b =>
                {
                    b.HasOne("HondaSensorChecker.Models.Operator", "Operator")
                        .WithMany("ZfBoxes")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HondaSensorChecker.Models.Product", "Product")
                        .WithMany("ZfBoxes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HondaSensorChecker.Models.SapWorkOrder", "SapWorkOrder")
                        .WithMany("ZfBoxes")
                        .HasForeignKey("SapWorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operator");

                    b.Navigation("Product");

                    b.Navigation("SapWorkOrder");
                });

            modelBuilder.Entity("HondaSensorChecker.Models.Operator", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Sensors");

                    b.Navigation("ZfBoxes");
                });

            modelBuilder.Entity("HondaSensorChecker.Models.Product", b =>
                {
                    b.Navigation("SapWorkOrders");

                    b.Navigation("Sensors");

                    b.Navigation("SupplierBoxes");

                    b.Navigation("ZfBoxes");
                });

            modelBuilder.Entity("HondaSensorChecker.Models.SapWorkOrder", b =>
                {
                    b.Navigation("Sensors");

                    b.Navigation("ZfBoxes");
                });

            modelBuilder.Entity("HondaSensorChecker.Models.SupplierBox", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("HondaSensorChecker.Models.ZfBox", b =>
                {
                    b.Navigation("Sensors");
                });
#pragma warning restore 612, 618
        }
    }
}
